development:
  adapter: postgresql
  encoding: unicode
  database: cradles_development
  pool: 5
  username: cradles

test:
  adapter: postgresql
  encoding: unicode
  database: cradles_test
  pool: 5
  username: cradles
  password:

production:
  adapter:  postgresql
  encoding: unicode
  pool: 5
  database: d14ju6c6k6cqp0
  username: ohmbzgyldmigwi
  password: BvrL3t37swo-RPq_-G4eq7GsGK
  host: ec2-54-243-223-143.compute-1.amazonaws.com
  port: 5432
