development:
  adapter: postgresql
  encoding: unicode
  database: cradles_development
  pool: 5
  username: cradles

test:
  adapter: postgresql
  encoding: unicode
  database: cradles_test
  pool: 5
  username: cradles
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: cradles_production
  pool: 5
  username: root
  password: UOMKgrM5R6zK66hN8IF0
  port: 37801
  host: cradles-george.azva.dotcloud.net
